/**
 * BE-E (mobile cinematic overhaul) -- monthly recap reads.
 *
 * Per lens 7 P1-1. The nightly job
 * (backend/src/jobs/monthlyRecapJob.ts) generates one
 * `monthly_recaps` row per active user on the 1st of each month at
 * 06:00 UTC. The mobile app reads via:
 *
 *   GET /recaps/latest        -- the most recent recap, or { recap: null }
 *   GET /recaps/:period_key   -- the recap for that month (YYYY-MM)
 *
 * Caches are short (60s) because the data is generated by a cron
 * and rarely changes within a day.
 */
import { Router, Request, Response, NextFunction } from 'express';
import { supabase } from '../lib/supabase';
import { AppError } from '../middleware/errorHandler';
import { requireActiveUser } from '../middleware/requireActiveUser';
import { cacheControl } from '../middleware/cache';

const router = Router();
router.use(requireActiveUser);

/**
 * GET /recaps/latest -- most recent recap for the user. Returns
 * { recap: null } if none exists (no workouts in the prior month).
 */
router.get('/latest', cacheControl(60), async (req: Request, res: Response, next: NextFunction) => {
  try {
    const userId = req.user!.id;
    const { data, error } = await supabase
      .from('monthly_recaps')
      .select('*')
      .eq('user_id', userId)
      .order('period_start', { ascending: false })
      .limit(1)
      .maybeSingle();

    if (error) return next(new AppError('DB_ERROR', 500, error.message));
    return res.json({ data: { recap: data ?? null } });
  } catch (err: any) {
    return next(new AppError('INTERNAL_ERROR', 500, err.message ?? 'Unexpected error'));
  }
});

/**
 * GET /recaps/:period_key -- recap for the given YYYY-MM. 404 if the
 * cron hasn't produced one for the user (no workouts in that month).
 */
router.get('/:period_key', cacheControl(60), async (req: Request, res: Response, next: NextFunction) => {
  try {
    const userId = req.user!.id;
    const period = req.params.period_key;
    if (!/^\d{4}-\d{2}$/.test(period)) {
      return next(new AppError('VALIDATION_ERROR', 422, 'period_key must be YYYY-MM'));
    }
    const { data, error } = await supabase
      .from('monthly_recaps')
      .select('*')
      .eq('user_id', userId)
      .eq('period_key', period)
      .maybeSingle();

    if (error) return next(new AppError('DB_ERROR', 500, error.message));
    if (!data) return next(new AppError('NOT_FOUND', 404, 'Recap not found for that period'));
    return res.json({ data: { recap: data } });
  } catch (err: any) {
    return next(new AppError('INTERNAL_ERROR', 500, err.message ?? 'Unexpected error'));
  }
});

export default router;
