CREATE TABLE user_settings (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES users(id) ON DELETE CASCADE UNIQUE NOT NULL,
  weight_unit VARCHAR(5) DEFAULT 'kg' CHECK (weight_unit IN ('kg','lbs')),
  default_rest_seconds INTEGER DEFAULT 90 CHECK (default_rest_seconds > 0),
  previous_values_mode VARCHAR(20) DEFAULT 'overall'
    CHECK (previous_values_mode IN ('overall','within_routine')),
  warm_up_sets_in_stats BOOLEAN DEFAULT false,
  keep_awake_during_workout BOOLEAN DEFAULT true,
  rpe_tracking_enabled BOOLEAN DEFAULT false,
  smart_superset_scrolling BOOLEAN DEFAULT true,
  inline_timer_enabled BOOLEAN DEFAULT true,
  live_pr_notification_enabled BOOLEAN DEFAULT true,
  timer_sound_volume INTEGER DEFAULT 80 CHECK (timer_sound_volume BETWEEN 0 AND 100),
  pr_sound_volume INTEGER DEFAULT 80 CHECK (pr_sound_volume BETWEEN 0 AND 100),
  warmup_calculator_steps JSONB DEFAULT '[{"percentage":40,"reps":10},{"percentage":60,"reps":5},{"percentage":80,"reps":3},{"percentage":90,"reps":1}]',
  plate_calculator_bar_kg DECIMAL(4,1) DEFAULT 20.0,
  notif_likes BOOLEAN DEFAULT true,
  notif_comments BOOLEAN DEFAULT true,
  notif_follows BOOLEAN DEFAULT true,
  notif_prs BOOLEAN DEFAULT true,
  notif_announcements BOOLEAN DEFAULT true,
  notif_leaderboard BOOLEAN DEFAULT true,
  notif_streak_milestones BOOLEAN DEFAULT true,
  notif_weekly_nudge BOOLEAN DEFAULT true,
  timezone VARCHAR(100) DEFAULT 'UTC',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
